kind: pipeline
type: docker
name: default

steps:
  - name: install dependencies
    image: node
    commands:
    - yarn

  - name: lint
    image: node
    commands:
    - yarn lint

  - name: test
    image: node
    commands:
    - yarn test

  - name: semantic-release
    image: gtramontina/semantic-release:15.13.3
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    entrypoint:
      - semantic-release
    when:
      branch: master
      event: push
