kind: pipeline
type: docker
name: default

steps:
  - name: install dependencies
    image: node
    commands:
    - yarn

  - name: lint
    image: node
    commands:
    - yarn lint

  - name: test
    image: node
    commands:
    - yarn test